apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sinatra-app.fullname" . }}
  labels:
    {{- include "sinatra-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sinatra-app.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sinatra-app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-db-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "sinatra-app.fullname" . }}
          env:
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.password.secretName }}
                  key: {{ .Values.database.password.secretKey }}
          command:
            - sh
            - -c
            - >-
              bin/rake db:create &&
              bin/rake db:migrate
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 4
