apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sinatra-app.fullname" . }}
  labels:
    {{- include "sinatra-app.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.customSecretEnv }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
